using System.Collections.Generic;
using Exanite.Arpg.Pathfinding.Graphs;
using UniRx.Async;
using UnityEngine;

namespace Exanite.Arpg.Pathfinding
{
    public class Pathfinder
    {
        private bool isPathValid;
        private List<Node> path = new List<Node>();

        private readonly Dictionary<Node, Node> parent = new Dictionary<Node, Node>();
        private readonly Dictionary<Node, float> fCost = new Dictionary<Node, float>();
        private readonly Dictionary<Node, float> gCost = new Dictionary<Node, float>();

        private readonly List<Node> open = new List<Node>();
        private readonly HashSet<Node> closed = new HashSet<Node>();

        private object syncRoot = new object();

        /// <summary>
        /// Is the current Path valid?
        /// </summary>
        public bool IsPathValid
        {
            get
            {
                return isPathValid;
            }

            set
            {
                isPathValid = value;
            }
        }

        /// <summary>
        /// Path generated by the <see cref="Pathfinder"/>
        /// </summary>
        public List<Node> Path
        {
            get
            {
                return path;
            }

            set
            {
                path = value;
            }
        }

        /// <summary>
        /// Attempts to find a path between the start and destination nodes
        /// </summary>
        public async UniTask<bool> FindPathAsync(Node start, Node destination, Heuristic heuristic = null)
        {
            await UniTask.SwitchToThreadPool();

            bool success;

            lock (syncRoot)
            {
                success = FindPath(start, destination, heuristic);
            }

            await UniTask.SwitchToMainThread();

            return success;
        }

        /// <summary>
        /// Attempts to find a path between the start and destination nodes
        /// </summary>
        public bool FindPath(Node start, Node destination, Heuristic heuristic = null)
        {
            if (heuristic == null)
            {
                heuristic = DefaultHeuristic;
            }

            if (destination.Type == NodeType.NonWalkable)
            {
                IsPathValid = false;

                return false;
            }

            CleanupPathfindingData();

            open.Add(start);
            fCost[start] = 0;
            gCost[start] = 0;

            Node current;
            bool success = false;

            while (open.Count > 0)
            {
                current = open[0];

                for (int i = 1; i < open.Count; i++)
                {
                    if (fCost[open[i]] < fCost[current])
                    {
                        current = open[i];
                    }
                }

                open.Remove(current);
                closed.Add(current);

                if (current == destination)
                {
                    success = true;

                    break;
                }

                foreach (var neighbor in current.GetConnectedNodes())
                {
                    if (neighbor.Type == NodeType.NonWalkable || closed.Contains(neighbor))
                    {
                        continue;
                    }

                    float newGCost = gCost[current] + heuristic(current, neighbor);

                    if (!gCost.ContainsKey(neighbor) || newGCost < gCost[neighbor])
                    {
                        gCost[neighbor] = newGCost;
                        parent[neighbor] = current;

                        if (!open.Contains(neighbor) && !closed.Contains(neighbor))
                        {
                            fCost[neighbor] = newGCost + heuristic(neighbor, destination);

                            open.Add(neighbor);
                        }
                    }
                }
            }

            if (success)
            {
                Path = RetracePath(start, destination);
            }

            CleanupPathfindingData();

            IsPathValid = success;

            return success;
        }

        /// <summary>
        /// Retraces the path from <paramref name="destination"/> to <paramref name="start"/> <para/>
        /// </summary>
        private List<Node> RetracePath(Node start, Node destination)
        {
            var list = new List<Node>();
            var current = destination;

            while (current != start)
            {
                list.Add(current);

                current = parent[current];
            }

            list.Reverse();

            return list;
        }

        /// <summary>
        /// Cleans up pathfinding data for the next use
        /// </summary>
        private void CleanupPathfindingData()
        {
            parent.Clear();
            fCost.Clear();
            gCost.Clear();

            open.Clear();
            closed.Clear();
        }

        /// <summary>
        /// Calculates the distance between two <see cref="Node"/>s
        /// By default the Heuristic returns the Euclidean distance between the two nodes
        /// </summary>
        public static float DefaultHeuristic(Node a, Node b)
        {
            return EuclideanHeuristic(a, b);
        }

        /// <summary>
        /// Returns the Euclidean Distance between two <see cref="Node"/>s
        /// </summary>
        public static float EuclideanHeuristic(Node a, Node b)
        {
            return Vector3.Distance(a.Position, b.Position);
        }

        /// <summary>
        /// Returns the Manhattan Distance between two <see cref="Node"/>s
        /// </summary>
        public static float ManhattanHeuristic(Node a, Node b)
        {
            float dx = Mathf.Abs(a.Position.x - b.Position.x);
            float dy = Mathf.Abs(a.Position.y - b.Position.y);
            float dz = Mathf.Abs(a.Position.z - b.Position.z);

            return dx + dy + dz;
        }
    }
}
