name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # Build
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       unityVersion: 
        - 2020.1.2f1
       targetPlatform:
        - StandaloneWindows64
    steps:
    # Checkout
    - uses: actions/checkout@v2
      with:
        lfs: false
    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-
    # Build
    - uses: webbertakken/unity-builder@v1.2
      with:
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}
        buildMethod: Exanite.Arpg.Editor.Builds.GameBuilder.BuildClientAndServer
    # Upload
    - uses: actions/upload-artifact@v1
      with:
        name: Build_${{ matrix.targetPlatform }}
        path: Builds
  # Activation - Use when changing Unity versions
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    # Request
    - uses: webbertakken/unity-request-manual-activation-file@v1.1
      id: getManualLicenseFile
      with:
        unityVersion: 2020.1.2f1
    # Upload
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
    # Activate by going to https://license.unity3d.com/manual and adding a secret 'UNITY_LICENSE' to the repo