name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       unityVersion: 
        - 2019.4.0f1
       targetPlatform:
        - StandaloneWindows64
    steps:
    # Checkout
    - uses: actions/checkout@v2
      with:
        lfs: false
    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('.github/cache_version') }}
    # Build
    - uses: webbertakken/unity-builder@v1.1
      with:
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}
        versioning: Semantic
    # Upload
    - uses: actions/upload-artifact@v1
      with:
        name: Build_${{ matrix.targetPlatform }}
        path: build
